<Project ToolsVersion="15.0">
  <ItemGroup>
    <PackageVersion Include="AdvancedSharpAdbClient" Version="3.5.15" />
    <PackageVersion Include="BouncyCastle.Cryptography" Version="2.7.0" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageVersion Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Converters" Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Extensions" Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Controls.Segmented" Version="8.2.251219" />
    <PackageVersion Include="DesktopFlyouts.WinUI" Version="1.4.0" />
    <PackageVersion Include="libphonenumber-csharp" Version="9.0.29" />
    <PackageVersion Include="MeaMod.DNS" Version="1.0.71" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Localization" Version="10.0.11" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="2.4.0" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2705" />
    <PackageVersion Include="NAudio" Version="2.2.1" />
    <PackageVersion Include="NetCoreServer" Version="8.0.7" />
    <PackageVersion Include="QRCoder" Version="1.7.0" />
    <PackageVersion Include="Serilog" Version="4.4.0" />
    <PackageVersion Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageVersion Include="sqlite-net-pcl" Version="1.11.272-beta" />
    <PackageVersion Include="SourceGear.sqlite3" Version="3.50.4.5" />
    <PackageVersion Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
    <PackageVersion Include="SQLitePCLRaw.config.e_sqlite3" Version="3.0.3" />
    <PackageVersion Include="SSH.NET" Version="2026.0.0" />
    <PackageVersion Include="Vanara.PInvoke.CldApi" Version="5.0.1" />
    <PackageVersion Include="Vanara.PInvoke.Ole" Version="5.0.1" />
    <PackageVersion Include="Vanara.PInvoke.Shell32" Version="5.0.1" />
  </ItemGroup>
</Project>
